# Generated by Django 5.1.4 on 2025-01-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadNotesOrQuestionPaper', '0002_remove_notes_description_questionpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='sem',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
